const menuData = {
  personalAlas: [
    {
      id: 1,
      name: "Combo 1",
      description: "3 piezas de ala",
      pictureUrl: require("../../assets/personales/combo1.webp"),
      price: "$12.000",
    },
    {
      id: 2,
      name: "Combo 2",
      description: "4 piezas de ala",
      pictureUrl: require("../../assets/personales/combo2.webp"),
      price: "$15.000",
    },
    {
      id: 3,
      name: "Combo 3",
      description: "6 piezas de ala",
      pictureUrl: require("../../assets/personales/combo3.webp"),
      price: "$18.500",
    },
    {
      id: 4,
      name: "Combo 4",
      description: "8 piezas de ala",
      pictureUrl: require("../../assets/personales/combo4.webp"),
      price: "$21.500",
    },
    {
      id: 5,
      name: "Combo 10",
      description: "10 piezas de ala",
      pictureUrl: require("../../assets/personales/combo10.webp"),
      price: "$24.000",
    },
  ],
  personalCostillas: [
    {
      id: 6,
      name: "Combo 6",
      description: "4 costillitas",
      pictureUrl: require("../../assets/personales/combo6.webp"),
      price: "$20.000",
    },
    {
      id: 7,
      name: "Combo 7",
      description: "6 costillitas",
      pictureUrl: require("../../assets/personales/combo7.webp"),
      price: "$24.000",
    },
    {
      id: 8,
      name: "Combo 8",
      description: "8 costillitas",
      pictureUrl: require("../../assets/personales/combo8.webp"),
      price: "$28.000",
    },
  ],
  personalMixto: [
    {
      id: 9,
      name: "Combo 5",
      description: "2 piezas de ala + 2 costillitas",
      pictureUrl: require("../../assets/personales/combo5.webp"),
      price: "$19.500",
    },
    {
      id: 10,
      name: "Combo 9",
      description: "4 piezas de ala + 4 costillitas",
      pictureUrl: require("../../assets/personales/combo9.webp"),
      price: "$24.000",
    },
    {
      id: 11,
      name: "Picada",
      description: "2 piezas de ala + 1 costillita + salchicha + nuggets + hievitos de codorniz",
      pictureUrl: require("../../assets/personales/picada.webp"),
      price: "$22.000",
    },
    {
      id: 12,
      name: "Salchipapa super especial",
      description: "Salchica premium + Trocitos de steak + Huevos de codorniz + Trocitos de platano maduro + Maiz tierno + Tocineta + Queso mozzarella",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$20.000",
    },
  ],

  Familiares: [
    {
      id: 13,
      name: "Pakman",
      description: "25 piezas de ala + papa fritas + croquetas de yuca + papa casco + gaseosa 1.5 lts",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$57.000",
    },
    {
      id: 14,
      name: "Super Pakman",
      description: "35 piezas de ala + papa fritas + croquetas de yuca + papa casco + gaseosa 1.5 lts",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$75.000",
    },
    {
      id: 15,
      name: "Pakman Mix 10",
      description: "10 piezas de ala + 8 costillas + papas fritas + croquetas de yuca + papa casco + gaseosa 10.5 lts",
      pictureUrl: require("../../assets/familiares/Pakmanmix10.webp"),
      price: "$58.000",
    },
    {
      id: 16,
      name: "Pakman Mix 15",
      description: "15 piezas de ala + 8 costillas + papas fritas + croquetas de yuca + papa casco + gaseosa 10.5 lts",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$64.000",
    },
    {
      id: 17,
      name: "Salchipapa Super Especial Familiar",
      description: "Salchipapa super especial familiar + 5 piezas de ala + gaseosa 10.5 lts",
      pictureUrl: require("../../assets/familiares/salchipapaespecial.webp"),
      price: "$57.000",
    },
  ],

  junior: [
    {
      id: 18,
      name: "Junior 1",
      description: "Salchipapa",
      pictureUrl: require("../../assets/junior/salchipapa.webp"),
      price: "$13.000",
    },
    {
      id: 19,
      name: "Junior 2",
      description: "Nuggets + huevos de codorniz",
      pictureUrl: require("../../assets/junior/nuggets.webp"),
      price: "$15.000",
    },
    {
      id: 20,
      name: "Happy Pakman",
      description: "Nuggets + papas caritas felices + salchicha + huevos de codorniz",
      pictureUrl: require("../../assets/junior/happy.webp"),
      price: "$15.500",
    },
    {
      id: 21,
      name: "Steak",
      description: "Filetes de pechuga apanados",
      pictureUrl: require("../../assets/junior/steak.webp"),
      price: "$15.000",
    },
  ],

  drinks: [
    {
      id: 1,
      name: "Costilla",
      description: "Unidad",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$4.000",
    },
    {
      id: 2,
      name: "Pieza de ala",
      description: "Unidad",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$3.500",
    },
    {
      id: 3,
      name: "Porcion de nueggets",
      description: "5 unidades",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$6.500",
    },
    {
      id: 4,
      name: "Huevos de codorniz",
      description: "5 unidades",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$4.500",
    },
    {
      id: 5,
      name: "Salchica",
      description: "Unidad",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$4.500",
    },
    {
      id: 6,
      name: "Papa francesa",
      description: "Porcion de 140 gr",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$6.000",
    },
    {
      id: 7,
      name: "Anillos de cebolla",
      description: "5 unidades",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$6.500",
    },
    {
      id: 8,
      name: "Croquetas de yuca",
      description: "4 unidades",
      pictureUrl: require("../../assets/adicionales/yuca.webp"),
      price: "$6.000",
    },
    {
      id: 9,
      name: "Adicion Steak",
      description: "Porcion de 140 gr",
      pictureUrl: require("../../assets/adicionales/steak.webp"),
      price: "$7.000",
    },
    {
      id: 10,
      name: "Caritas felices",
      description: "5 unidades",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$6.000",
    },
    {
      id: 11,
      name: "Papa casco",
      description: "Porcion de 130 gr",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$6.000",
    },
  ],
  bebidas: [
    {
      id: 1,
      name: "Bebida vaso",
      description: "",
      pictureUrl: require("../../assets/bebidas/vaso.jpg"),
      price: "$2.000",
    },
    {
      id: 2,
      name: "Club Colombia",
      description: "",
      pictureUrl: require("../../assets/bebidas/clubcolombia.jpg"),
      price: "$6.000",
    },
    {
      id: 3,
      name: "Gaseosa 3 lts",
      description: "",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$8.500",
    },
    {
      id: 4,
      name: "Gaseosa 1.5 lts",
      description: "",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$6.000",
    },
    {
      id: 5,
      name: "Coca-Cola 400 ml",
      description: "",
      pictureUrl: require("../../assets/bebidas/cocacola400.png"),
      price: "$3.500",
    },
    {
      id: 6,
      name: "Agua botella pet",
      description: "",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$1.500",
    },
    {
      id: 7,
      name: "Agua botella",
      description: "",
      pictureUrl: require("../../assets/pakman.webp"),
      price: "$2.000",
    },
    {
      id: 8,
      name: "Coronita",
      description: "",
      pictureUrl: require("../../assets/bebidas/coronita.jpg"),
      price: "$6.000",
    },
    {
      id: 9,
      name: "Coca-Cola 237 ml",
      description: "",
      pictureUrl: require("../../assets/bebidas/cocacola237.png"),
      price: "$3.000",
    },
  ],
  Jugos: [
    {
      id: 1,
      name: "Fresa",
      description: "",
      pictureUrl: require("../../assets/jugos/fresa.webp"),
      price: "",
    },
    {
      id: 2,
      name: "Mango",
      description: "",
      pictureUrl: require("../../assets/jugos/mango.webp"),
      price: "",
    },
    {
      id: 3,
      name: "Feijoa",
      description: "",
      pictureUrl: require("../../assets/jugos/freijoa.webp"),
      price: "",
    },
    {
      id: 4,
      name: "Lulo",
      description: "",
      pictureUrl: require("../../assets/jugos/lulo.webp"),
      price: "",
    },
    {
      id: 5,
      name: "Uva",
      description: "",
      pictureUrl: require("../../assets/jugos/uva.webp"),
      price: "",
    },
    {
      id: 6,
      name: "Mora",
      description: "",
      pictureUrl: require("../../assets/jugos/mora.webp"),
      price: "",
    },
    {
      id: 7,
      name: "Piña",
      description: "",
      pictureUrl: require("../../assets/jugos/piña.webp"),
      price: "",
    },
    {
      id: 8,
      name: "Guanabana",
      description: "",
      pictureUrl: require("../../assets/jugos/guanabana.webp"),
      price: "",
    },
    {
      id: 9,
      name: "Maracuya",
      description: "",
      pictureUrl: require("../../assets/jugos/maracuya.webp"),
      price: "",
    },
    {
      id: 10,
      name: "Frutos rojos",
      description: "",
      pictureUrl: require("../../assets/jugos/frutosrojos.webp"),
      price: "",
    },
    {
      id: 11,
      name: "Crema de limon",
      description: "",
      pictureUrl: require("../../assets/jugos/cremadelimon.webp"),
      price: "",
    },
  ],
  limandas: [
    {
      id: 1,
      name: "Limonada natural",
      description: "",
      pictureUrl: require("../../assets/jugos/limonada.webp"),
      price: "$7.000",
    },
    {
      id: 2,
      name: "Limonada hierbabuena",
      description: "",
      pictureUrl: require("../../assets/jugos/limonadahb.webp"),
      price: "$7.500",
    },
    {
      id: 3,
      name: "Limonada cerezada",
      description: "",
      pictureUrl: require("../../assets/jugos/limondadcereza.webp"),
      price: "$7.500",
    },
    {
      id: 4,
      name: "Limonada de coco",
      description: "",
      pictureUrl: require("../../assets/jugos/lomonadacoco.webp"),
      price: "$8.000",
    },
  ],
  salsas: [
    {
      id: 1,
      name: "BBQ",
      description: "",
      pictureUrl: require("../../assets/dinner/img1.png"),
      price: "",
    },
    {
      id: 2,
      name: "Miel mostaza",
      description: "",
      pictureUrl: require("../../assets/dinner/img2.png"),
      price: "",
    },
    {
      id: 3,
      name: "Chile dulce",
      description: "",
      pictureUrl: require("../../assets/dinner/img3.png"),
      price: "",
    },
    {
      id: 4,
      name: "Bufalo medio",
      description: "",
      pictureUrl: require("../../assets/dinner/img4.png"),
      price: "",
    },
    {
      id: 5,
      name: "Bufalo fuerte",
      description: "",
      pictureUrl: require("../../assets/dinner/img4.png"),
      price: "",
    },
    {
      id: 6,
      name: "Parmesano",
      description: "",
      pictureUrl: require("../../assets/dinner/img4.png"),
      price: "",
    },
    {
      id: 7,
      name: "Mango",
      description: "",
      pictureUrl: require("../../assets/dinner/img4.png"),
      price: "",
    },
  ],
};

export default menuData;
